name: Deploy-Application-Service 
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
      - uat      
    # paths:
    #   - '.github/workflows/deploy-application-service.yml'
    #   - 'python-app/**'
    #   - 'build/**'

env:
  # TARGET_DIR: build/
  TF_ENVIRONMENT: ${{ github.ref == 'refs/heads/dev' && 'dev' || github.ref == 'refs/heads/uat' && 'uat' || github.ref == 'refs/heads/master' && 'prod' ||'unknown' }}
  TF_REGION: eu-west-1
      
concurrency:
  group: Ci-${{ github.ref == 'refs/heads/dev' && 'dev' || github.ref == 'refs/heads/uat' && 'uat' || github.ref == 'refs/heads/master' && 'prod' ||'unknown' }}
  cancel-in-progress: false

permissions:
  contents: write # to add SBOM 
  id-token: write
  pull-requests: write # to upload code scanning results

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate input summary
        run: |
         echo "## Inputs" >> $GITHUB_STEP_SUMMARY
         echo "Environment: ${{ env.TF_ENVIRONMENT }}"
